version: '3'
services:
  mysql:
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: akaunting_root_password
      MYSQL_DATABASE: akaunting_db
      MYSQL_USER: akaunting_admin
      MYSQL_PASSWORD: akaunting_password
  web:
    image: akaunting
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    environment:
      APP_DEBUG: "true"
    links:
      - mysql
